version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - aws --version
      - $(aws ecr get-login --no-include-email --region ap-northeast-2)
      - npm install yarn
  build:
    commands:
      - docker build -t testECS .
  post_build:
    commands:
      - docker tag testECS:latest 190594267513.dkr.ecr.ap-northeast-2.amazonaws.com/docker-test:latest
      - docker push 190594267513.dkr.ecr.ap-northeast-2.amazonaws.com/docker-test:latest
      - echo Writing image definitions file...
      - printf '[{"name":"docker-test-container","imageUri":"%s"}]' 190594267513.dkr.ecr.ap-northeast-2.amazonaws.com/docker-test:latest > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
